
'MantenimientoDB
Sub MantenimientoDB()
    busqSocio.Show (0)
End Sub

'Grupo
Sub MantenimientoGrupo()
    mGrupos.Show (0)
End Sub

'Accionista
Sub MantenimientoAccionista()
    mAccionista.Show (0)
End Sub

'Gerencia
Sub MantenimientoGerencia()
    mGerencia.Show (0)
End Sub

'Representante Legal
Sub MantenimientoRepresentante()
    mRepresentante.Show (0)
End Sub

'Nacionalidad
Sub MantenimientoNacionalidad()
    mNacionalidad.Show (0)
End Sub

'Formacion
Sub MantenimientoFormacion()
    mFormacion.Show (0)
End Sub

Sub ModificarFichaCliente()
    
    On Error Resume Next
    idFicha = ActiveSheet.Cells(Selection.Row, ActiveSheet.Range("ID_FICHA").Column).Value
    On Error GoTo 0
    
    If Selection.count = 1 Then
        If ActiveSheet.Name = "MAIN" Then
            If idFicha > 0 Then
                desdeHoja = True
                modFicha.Show (0)
            End If
        End If
    End If
End Sub

'ActualizarMain
Sub ActualizarMain()
    If Hoja1.Range("HISTORICO") = "SI" Then
        If Hoja1.Range("INTEGRANTES_TIPO") = "TODOS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_INTEGRANTE, TIPO_INTEGRANTE, PARTICIPACION, NOMBRE_TIPO_FICHA, FECHA_FICHA, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        " ((((((((FICHA_PRESTAMO FP LEFT JOIN PRESTAMO P ON P.ID_PRESTAMO = FP.ID_PRESTAMO_FK)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN (SELECT NOMBRE_INTEGRANTE, PARTICIPACION, TIPO_INTEGRANTE, ID_FICHA_FK" & _
                        "           FROM (SELECT NOMBRE_ACCIONISTA AS NOMBRE_INTEGRANTE, PARTICIPACION / 100 AS PARTICIPACION, 'ACCIONISTA' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_ACCIONISTA FA LEFT JOIN ACCIONISTA A ON FA.ID_ACCIONISTA_FK = A.ID_ACCIONISTA WHERE A.ANULADO = FALSE AND FA.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        "                   UNION ALL SELECT NOMBRE_GERENCIA AS NOMBRE_INTEGRANTE, 0 AS PARTICIPACION, 'GERENCIA' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_GERENCIA FG LEFT JOIN GERENCIA G ON FG.ID_GERENCIA_FK = G.ID_GERENCIA WHERE G.ANULADO = FALSE AND FG.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        "                   UNION ALL SELECT NOMBRE_REPRESENTANTE AS NOMBRE_INTEGRANTE, 0 AS PARTICIPACION, 'REPRESENTANTE' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_REPRESENTANTE FR LEFT JOIN REPRESENTANTE R ON FR.ID_REPRESENTANTE_FK = R.ID_REPRESENTANTE WHERE R.ANULADO = FALSE AND FR.ID_FICHA_MOD_SIGUIENTE = 0)) AS INTE ON INTE.ID_FICHA_FK = F.ID_FICHA" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP.ANULADO = FALSE" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FECHA_FICHA DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC, TIPO_INTEGRANTE"
        End If
        
        If Hoja1.Range("INTEGRANTES_TIPO") = "ACCIONISTAS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_ACCIONISTA, 'ACCIONISTA', PARTICIPACION / 100, NOMBRE_TIPO_FICHA, FECHA_FICHA, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        " ((((((((((FICHA_PRESTAMO FP LEFT JOIN PRESTAMO P ON P.ID_PRESTAMO = FP.ID_PRESTAMO_FK)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN FICHA_ACCIONISTA FA ON F.ID_FICHA = FA.ID_FICHA_FK)" & _
                        " LEFT JOIN ACCIONISTA A ON FA.ID_ACCIONISTA_FK = A.ID_ACCIONISTA)" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP.ANULADO = FALSE" & _
                        "   AND A.ANULADO = FALSE" & _
                        "   AND FA.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FECHA_FICHA DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
        End If
        
        If Hoja1.Range("INTEGRANTES_TIPO") = "GERENCIAS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_GERENCIA, 'GERENCIA', 'NO APLICA', NOMBRE_TIPO_FICHA, FECHA_FICHA, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        " ((((((((((FICHA_PRESTAMO FP LEFT JOIN PRESTAMO P ON P.ID_PRESTAMO = FP.ID_PRESTAMO_FK)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN FICHA_GERENCIA FG ON F.ID_FICHA = FG.ID_FICHA_FK)" & _
                        " LEFT JOIN GERENCIA GE ON FG.ID_GERENCIA_FK = GE.ID_GERENCIA)" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP.ANULADO = FALSE" & _
                        "   AND GE.ANULADO = FALSE" & _
                        "   AND FG.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FECHA_FICHA DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
                        
        End If
        
        If Hoja1.Range("INTEGRANTES_TIPO") = "REPRESENTANTES LEGALES" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_REPRESENTANTE, 'TEPRESENTANTE', 'NO APLICA', NOMBRE_TIPO_FICHA, FECHA_FICHA, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        " ((((((((((FICHA_PRESTAMO FP LEFT JOIN PRESTAMO P ON P.ID_PRESTAMO = FP.ID_PRESTAMO_FK)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN FICHA_REPRESENTANTE FR ON F.ID_FICHA = FR.ID_FICHA_FK)" & _
                        " LEFT JOIN REPRESENTANTE R ON FR.ID_REPRESENTANTE_FK = R.ID_REPRESENTANTE)" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP.ANULADO = FALSE" & _
                        "   AND R.ANULADO = FALSE" & _
                        "   AND FR.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FECHA_FICHA DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
        End If
    Else
        If Hoja1.Range("INTEGRANTES_TIPO") = "TODOS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_INTEGRANTE, TIPO_INTEGRANTE, PARTICIPACION, NOMBRE_TIPO_FICHA, MFP.MAXFF, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA" & _
                    " FROM (((((((((PRESTAMO P LEFT JOIN (SELECT FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF, MAX(FP.FECHA_INGRESA) AS MAXFI FROM FICHA_PRESTAMO FP RIGHT JOIN (SELECT ID_PRESTAMO_FK AS MAXIDPREST, MAX(FECHA_FICHA_P) AS MAXFF FROM FICHA_PRESTAMO GROUP BY ID_PRESTAMO_FK) MFP ON MFP.MAXIDPREST = FP.ID_PRESTAMO_FK AND MFP.MAXFF = FP.FECHA_FICHA_P GROUP BY FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF) FP ON FP.ID_PRESTAMO_FK = P.ID_PRESTAMO)" & _
                    " LEFT JOIN FICHA_PRESTAMO FP2 ON FP2.ID_PRESTAMO_FK = FP.ID_PRESTAMO_FK AND FP2.ID_FICHA_FK = FP.ID_FICHA_FK AND FP2.FECHA_FICHA_P = FP.MAXFF AND FP2.FECHA_INGRESA = FP.MAXFI)" & _
                    " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                    " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                    " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                    " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                    " LEFT JOIN TIPO_FICHA TF ON FP2.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                    " LEFT JOIN FICHA F ON F.ID_FICHA = FP2.ID_FICHA_FK)" & _
                    " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                    " LEFT JOIN (SELECT NOMBRE_INTEGRANTE, PARTICIPACION, TIPO_INTEGRANTE, ID_FICHA_FK" & _
                    "           FROM (SELECT NOMBRE_ACCIONISTA AS NOMBRE_INTEGRANTE, PARTICIPACION / 100 AS PARTICIPACION, 'ACCIONISTA' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_ACCIONISTA FA LEFT JOIN ACCIONISTA A ON FA.ID_ACCIONISTA_FK = A.ID_ACCIONISTA WHERE A.ANULADO = FALSE AND FA.ID_FICHA_MOD_SIGUIENTE = 0" & _
                    "                   UNION ALL SELECT NOMBRE_GERENCIA AS NOMBRE_INTEGRANTE, 0 AS PARTICIPACION, 'GERENCIA' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_GERENCIA FG LEFT JOIN GERENCIA G ON FG.ID_GERENCIA_FK = G.ID_GERENCIA WHERE G.ANULADO = FALSE AND FG.ID_FICHA_MOD_SIGUIENTE = 0" & _
                    "                   UNION ALL SELECT NOMBRE_REPRESENTANTE AS NOMBRE_INTEGRANTE, 0 AS PARTICIPACION, 'REPRESENTANTE' AS TIPO_INTEGRANTE, ID_FICHA_FK FROM FICHA_REPRESENTANTE FR LEFT JOIN REPRESENTANTE R ON FR.ID_REPRESENTANTE_FK = R.ID_REPRESENTANTE WHERE R.ANULADO = FALSE AND FR.ID_FICHA_MOD_SIGUIENTE = 0)) AS INTE ON INTE.ID_FICHA_FK = F.ID_FICHA" & _
                    " WHERE S.ANULADO = FALSE" & _
                    "   AND P.ANULADO = FALSE" & _
                    "   AND F.ANULADO = FALSE" & _
                    "   AND FP2.ANULADO = FALSE" & _
                    " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, MFP.MAXFF DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC, TIPO_INTEGRANTE"
        End If
        
        If Hoja1.Range("INTEGRANTES_TIPO") = "ACCIONISTAS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_ACCIONISTA, 'ACCIONISTA', PARTICIPACION / 100, NOMBRE_TIPO_FICHA, FP.MAXFF, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                    " (((((((((((PRESTAMO P LEFT JOIN (SELECT FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF, MAX(FP.FECHA_INGRESA) AS MAXFI FROM FICHA_PRESTAMO FP RIGHT JOIN (SELECT ID_PRESTAMO_FK AS MAXIDPREST, MAX(FECHA_FICHA_P) AS MAXFF FROM FICHA_PRESTAMO GROUP BY ID_PRESTAMO_FK) MFP ON MFP.MAXIDPREST = FP.ID_PRESTAMO_FK AND MFP.MAXFF = FP.FECHA_FICHA_P GROUP BY FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF) FP ON FP.ID_PRESTAMO_FK = P.ID_PRESTAMO)" & _
                    " LEFT JOIN FICHA_PRESTAMO FP2 ON FP2.ID_PRESTAMO_FK = FP.ID_PRESTAMO_FK AND FP2.ID_FICHA_FK = FP.ID_FICHA_FK AND FP2.FECHA_FICHA_P = FP.MAXFF AND FP2.FECHA_INGRESA = FP.MAXFI)" & _
                    " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                    " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                    " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                    " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                    " LEFT JOIN TIPO_FICHA TF ON FP2.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                    " LEFT JOIN FICHA F ON F.ID_FICHA = FP2.ID_FICHA_FK)" & _
                    " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                    " LEFT JOIN FICHA_ACCIONISTA FA ON F.ID_FICHA = FA.ID_FICHA_FK)" & _
                    " LEFT JOIN ACCIONISTA A ON FA.ID_ACCIONISTA_FK = A.ID_ACCIONISTA)" & _
                    " WHERE S.ANULADO = FALSE" & _
                    "   AND P.ANULADO = FALSE" & _
                    "   AND F.ANULADO = FALSE" & _
                    "   AND FP2.ANULADO = FALSE" & _
                    "   AND A.ANULADO = FALSE" & _
                    "   AND FA.ID_FICHA_MOD_SIGUIENTE = 0" & _
                    " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FP.MAXFF DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
        End If
        If Hoja1.Range("INTEGRANTES_TIPO") = "GERENCIAS" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_GERENCIA, 'GERENCIA', 'NO APLICA', NOMBRE_TIPO_FICHA, FP.MAXFF, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        " (((((((((((PRESTAMO P LEFT JOIN (SELECT FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF, MAX(FP.FECHA_INGRESA) AS MAXFI FROM FICHA_PRESTAMO FP RIGHT JOIN (SELECT ID_PRESTAMO_FK AS MAXIDPREST, MAX(FECHA_FICHA_P) AS MAXFF FROM FICHA_PRESTAMO GROUP BY ID_PRESTAMO_FK) MFP ON MFP.MAXIDPREST = FP.ID_PRESTAMO_FK AND MFP.MAXFF = FP.FECHA_FICHA_P GROUP BY FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF) FP ON FP.ID_PRESTAMO_FK = P.ID_PRESTAMO)" & _
                    " LEFT JOIN FICHA_PRESTAMO FP2 ON FP2.ID_PRESTAMO_FK = FP.ID_PRESTAMO_FK AND FP2.ID_FICHA_FK = FP.ID_FICHA_FK AND FP2.FECHA_FICHA_P = FP.MAXFF AND FP2.FECHA_INGRESA = FP.MAXFI)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP2.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP2.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN FICHA_GERENCIA FG ON F.ID_FICHA = FG.ID_FICHA_FK)" & _
                        " LEFT JOIN GERENCIA GE ON FG.ID_GERENCIA_FK = GE.ID_GERENCIA)" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP2.ANULADO = FALSE" & _
                        "   AND GE.ANULADO = FALSE" & _
                        "   AND FG.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FP.MAXFF DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
                        
        End If
        
        If Hoja1.Range("INTEGRANTES_TIPO") = "REPRESENTANTES LEGALES" Then
            strSQL = "SELECT ID_FICHA_PRESTAMO, ID_FICHA, ID_FICHA_MOD, NOMBRE_GRUPO, DOI, CODIGO_SOCIO, NOMBRE_SOCIO, NOMBRE_REPRESENTANTE, 'REPRESENTANTE', 'NO APLICA', NOMBRE_TIPO_FICHA, FP.MAXFF, SOLICITUD, NOMBRE_PRODUCTO, NOMBRE_MONEDA, MONTO, FECHA_INGRESA FROM " & _
                        "(((((((((((PRESTAMO P LEFT JOIN (SELECT FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF, MAX(FP.FECHA_INGRESA) AS MAXFI FROM FICHA_PRESTAMO FP RIGHT JOIN (SELECT ID_PRESTAMO_FK AS MAXIDPREST, MAX(FECHA_FICHA_P) AS MAXFF FROM FICHA_PRESTAMO GROUP BY ID_PRESTAMO_FK) MFP ON MFP.MAXIDPREST = FP.ID_PRESTAMO_FK AND MFP.MAXFF = FP.FECHA_FICHA_P GROUP BY FP.ID_PRESTAMO_FK, FP.ID_FICHA_FK, MFP.MAXFF) FP ON FP.ID_PRESTAMO_FK = P.ID_PRESTAMO)" & _
                    " LEFT JOIN FICHA_PRESTAMO FP2 ON FP2.ID_PRESTAMO_FK = FP.ID_PRESTAMO_FK AND FP2.ID_FICHA_FK = FP.ID_FICHA_FK AND FP2.FECHA_FICHA_P = FP.MAXFF AND FP2.FECHA_INGRESA = FP.MAXFI)" & _
                        " LEFT JOIN PRODUCTO PR ON PR.ID_PRODUCTO = P.ID_PRODUCTO_FK)" & _
                        " LEFT JOIN MONEDA M ON M.ID_MONEDA = P.ID_MONEDA_FK)" & _
                        " LEFT JOIN SOCIO S ON S.ID_SOCIO = P.ID_SOCIO_FK)" & _
                        " LEFT JOIN GRUPO G ON S.ID_GRUPO_FK = G.ID_GRUPO)" & _
                        " LEFT JOIN TIPO_FICHA TF ON FP2.ID_TIPO_FICHA_FK = TF.ID_TIPO_FICHA)" & _
                        " LEFT JOIN FICHA F ON F.ID_FICHA = FP2.ID_FICHA_FK)" & _
                        " LEFT JOIN (SELECT FM.ID_FICHA_FK, FM.ID_FICHA_MOD, FM.FECHA_FICHA, FM.FECHA_MODIFICA, FM.USUARIO_MODIFICA, EXTENSION FROM FICHA_MOD FM RIGHT JOIN (SELECT ID_FICHA_FK, MAX(FECHA_MODIFICA) AS ULTMOD FROM FICHA_MOD WHERE ANULADO = FALSE GROUP BY ID_FICHA_FK) AS FFMAX ON FFMAX.ULTMOD = FM.FECHA_MODIFICA AND FFMAX.ID_FICHA_FK = FM.ID_FICHA_FK) AS FFM ON FFM.ID_FICHA_FK = F.ID_FICHA)" & _
                        " LEFT JOIN FICHA_REPRESENTANTE FR ON F.ID_FICHA = FR.ID_FICHA_FK)" & _
                        " LEFT JOIN REPRESENTANTE R ON FR.ID_REPRESENTANTE_FK = R.ID_REPRESENTANTE)" & _
                        " WHERE S.ANULADO = FALSE" & _
                        "   AND P.ANULADO = FALSE" & _
                        "   AND F.ANULADO = FALSE" & _
                        "   AND FP2.ANULADO = FALSE" & _
                        "   AND R.ANULADO = FALSE" & _
                        "   AND FR.ID_FICHA_MOD_SIGUIENTE = 0" & _
                        " ORDER BY NOMBRE_GRUPO, NOMBRE_SOCIO, ID_PRESTAMO, FP.MAXFF DESC, ID_FICHA, ID_FICHA_MOD, ID_FICHA_PRESTAMO, ID_TIPO_FICHA DESC"
        End If
    End If
    
    OpenDB
    On Error GoTo Handle:
    rs.Open strSQL, cnn, adOpenKeyset, adLockOptimistic
    On Error GoTo 0
    
    Hoja1.Range(Hoja1.Range("dataSet"), Hoja1.Range("dataSet").End(xlDown)).EntireRow.ClearContents
    If rs.RecordCount > 0 Then
        Hoja1.Range("dataSet").CopyFromRecordset rs
        
        'Intercalar Color
        If Hoja1.Range("dataSet").Offset(1, 0) = "" Then
            Hoja1.Range("ALTERNADO").AutoFill Destination:=Range(Hoja1.Range("ALTERNADO"), Hoja1.Range("ALTERNADO").Offset(1, 0))
        Else
            If Hoja1.Range("dataSet").End(xlDown).Offset(1, 0) = "" Then
                Hoja1.Range("ALTERNADO").AutoFill Destination:=Range(Hoja1.Range("ALTERNADO"), Hoja1.Range("dataSet").End(xlDown).Offset(0, -1))
            Else
                Hoja1.Range("ALTERNADO").AutoFill Destination:=Range(Hoja1.Range("ALTERNADO"), Hoja1.Range("dataSet").End(xlDown).End(xlDown).Offset(0, -1))
            End If
        End If
        Hoja1.Range("PARTICIPACION").EntireColumn.NumberFormat = "0.00%"
        Hoja1.Range("MONTO").EntireColumn.NumberFormat = "#,##0.00"
        Hoja1.Range("FECHA_REGISTRO").EntireColumn.NumberFormat = "dd/mm/yyyy hh:mm:ss"
        
    End If
Handle:
    If cnn.Errors.count > 0 Then
        'Log del Error
        Call Error_Handle(cnn.Errors.Item(0).Source, "Módulo2 - ActualizarMain", strSQL, cnn.Errors.Item(0).Number, cnn.Errors.Item(0).Description)
    End If
    cnn.Errors.Clear
    closeRS
End Sub

Sub VerFichaCliente()

    If Selection.count = 1 Then
        On Error GoTo Handle:
        idMod = ActiveSheet.Cells(Selection.Row, ActiveSheet.Range("ID_FICHA_MOD").Column).Value
        On Error GoTo 0
        
        If ActiveSheet.Name = "MAIN" And idMod <> 0 Then
            If idFicha > 0 Then
                
                strSQL = "SELECT EXTENSION FROM FICHA_MOD WHERE ID_FICHA_MOD = " & idMod
                                 
                OpenDB
                On Error GoTo Handle:
                rs.Open strSQL, cnn, adOpenKeyset, adLockOptimistic
                On Error GoTo 0
                
                On Error Resume Next
                ActiveWorkbook.FollowHyperlink ActiveWorkbook.Path & Application.PathSeparator & "RECURSOS" & Application.PathSeparator & idMod & "." & rs.Fields("EXTENSION").Value
                On Error GoTo 0
                
            End If
        End If
    End If
Handle:
    If cnn.Errors.count > 0 Then
        'Log del Error
        Call Error_Handle(cnn.Errors.Item(0).Source, "Módulo2 - VerFichaCliente", strSQL, cnn.Errors.Item(0).Number, cnn.Errors.Item(0).Description)
    End If
    cnn.Errors.Clear
    closeRS
End Sub
